# Site settings
title: Melheffe |
email: chris@melheffe.com
description: "Development merges design to bring you ther best User Experience on top of a carefully elaborated piece of software with the latest technology available to create a perfect harmony between functionality and appearance."
baseurl: ""
url: "http://www.melheffe.com"
github_username:  melheffe

